# Generated by Django 4.2.1 on 2023-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='inStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=4, default='', max_digits=19),
            preserve_default=False,
        ),
    ]
